In [1]:
import numpy as np
import pandas as pd
import os
POSTGRES_PASSWORD = os.getenv('POSTGRES_PASSWORD')
import psycopg2
from sqlalchemy import create_engine

In [2]:
bills=pd.read_csv('Data/bills.csv')              
congress_members=pd.read_csv('Data/congress_members.csv')  
os_legislators=pd.read_csv('Data/os_legislators.csv')
committee_members=pd.read_csv('Data/committee_members.csv')  
leadership=pd.read_csv('Data/leadership.csv')        
terms=pd.read_csv('Data/terms.csv')
committees=pd.read_csv('Data/committees.csv')         
os_contributions=pd.read_csv('Data/os_contributions.csv')  
votingaffinity=pd.read_csv('Data/votingaffinity.csv')

# Bills

In [3]:
bills.columns = [x.lower() for x in bills.columns]
bills.columns = [x.replace('.', '_') for x in bills.columns]
bills.columns

Index(['congress', 'introduceddate', 'number', 'title', 'type', 'url',
       'latestaction_actiondate', 'latestaction_text', 'policyarea_name',
       'amendmentnumber', 'latestaction', 'latestaction_actiontime'],
      dtype='object')

In [4]:
bills.head(3).T

,0,1,2
congress,118,118,118
introduceddate,2023-10-04,2023-09-29,2023-09-27
number,405.0,2998.0,373.0
title,A resolution expressing support for the design...,Land-Grant Research Equity and Accountability Act,A resolution designating the week of September...
type,SRES,S,SRES
url,https://api.congress.gov/v3/bill/118/sres/405?...,https://api.congress.gov/v3/bill/118/s/2998?fo...,https://api.congress.gov/v3/bill/118/sres/373?...
latestaction_actiondate,2023-10-04,2023-09-29,2023-09-27
latestaction_text,"Submitted in the Senate, considered, and agree...",Read twice and referred to the Committee on Ag...,"Submitted in the Senate, considered, and agree..."
policyarea_name,Armed Forces and National Security,Agriculture and Food,NaN
amendmentnumber,NaN,NaN,NaN
latestaction,NaN,NaN,NaN
latestaction_actiontime,NaN,NaN,NaN

In [5]:
bills = bills.drop(['congress'], axis=1)

In [40]:
bills.head(1).T

                                                                         0
introduceddate                                                  2023-10-04
number                                                               405.0
title                    A resolution expressing support for the design...
type                                                                  SRES
url                      https://api.congress.gov/v3/bill/118/sres/405?...
latestaction_actiondate                                         2023-10-04
latestaction_text        Submitted in the Senate, considered, and agree...
policyarea_name                         Armed Forces and National Security
amendmentnumber                                                        NaN
latestaction                                                           NaN
latestaction_actiontime                                                NaN

## congress_members

In [6]:
congress_members.columns = [x.lower() for x in congress_members.columns]
congress_members.columns = [x.replace('.', '_') for x in congress_members.columns]
congress_members.columns

Index(['bioguideid', 'birthyear', 'currentmember', 'directordername',
       'firstname', 'honorificname', 'invertedordername', 'lastname',
       'officialwebsiteurl', 'partyhistory', 'state', 'terms', 'updatedate',
       'addressinformation_city', 'addressinformation_district',
       'addressinformation_officeaddress', 'addressinformation_phonenumber',
       'addressinformation_zipcode', 'cosponsoredlegislation_count',
       'cosponsoredlegislation_url', 'depiction_attribution',
       'depiction_imageurl', 'sponsoredlegislation_count',
       'sponsoredlegislation_url', 'middlename', 'suffixname', 'nickname',
       'leadership', 'district'],
      dtype='object')

In [7]:
congress_members = congress_members.drop(['terms', 'leadership',
                                         'partyhistory'], axis=1)

In [8]:
congress_members.head(3).T

,0,1,2
bioguideid,B000944,C000127,C000141
birthyear,1952,1958,1943
currentmember,True,True,True
directordername,Sherrod Brown,Maria Cantwell,Benjamin L. Cardin
firstname,Sherrod,Maria,Ben
honorificname,Mr.,Ms.,Mr.
invertedordername,"Brown, Sherrod","Cantwell, Maria","Cardin, Benjamin L."
lastname,Brown,Cantwell,Cardin
officialwebsiteurl,https://www.brown.senate.gov/,https://www.cantwell.senate.gov,https://www.cardin.senate.gov/
state,Ohio,Washington,Maryland
updatedate,2023-04-01T12:42:12Z,2023-04-01T12:42:12Z,2023-04-01T12:42:13Z
addressinformation_city,Washington,Washington,Washington
addressinformation_district,DC,DC,DC
addressinformation_officeaddress,"503 Hart Senate Office Building Washington, DC...","511 Hart Senate Office Building Washington, DC...","509 Hart Senate Office Building Washington, DC..."
addressinformation_phonenumber,(202) 224-2315,(202) 224-3441,(202) 224-4524
addressinformation_zipcode,20515,20515,20515
cosponsoredlegislation_count,7873,3923,6100
cosponsoredlegislation_url,https://api.congress.gov/v3/member/B000944/cos...,https://api.congress.gov/v3/member/C000127/cos...,https://api.congress.gov/v3/member/C000141/cos...
depiction_attribution,"<a href=""http://www.senate.gov/artandhistory/h...","<a href=""http://www.senate.gov/artandhistory/h...","<a href=""http://www.senate.gov/artandhistory/h..."
depiction_imageurl,https://www.congress.gov/img/member/b000944_20...,https://www.congress.gov/img/member/c000127_20...,https://www.congress.gov/img/member/c000141_20...
sponsoredlegislation_count,1389.0,882.0,1265.0
sponsoredlegislation_url,https://api.congress.gov/v3/member/B000944/spo...,https://api.congress.gov/v3/member/C000127/spo...,https://api.congress.gov/v3/member/C000141/spo...
middlename,NaN,NaN,NaN
suffixname,NaN,NaN,NaN
nickname,NaN,NaN,NaN
district,NaN,NaN,NaN

## Terms

In [9]:
terms.columns = [x.lower() for x in terms.columns]
terms.columns = [x.replace('.', '_') for x in terms.columns]
terms.head(3).T

                  0        1        2
chamber      Senate   Senate   Senate
congress        107      108      109
endyear      2003.0   2005.0   2007.0
membertype  Senator  Senator  Senator
startyear      2002     2003     2005
statecode        TX       TX       TX
statename     Texas    Texas    Texas
bioguideid  C001056  C001056  C001056
district        NaN      NaN      NaN

## Leadership

In [10]:
leadership.columns = [x.lower() for x in leadership.columns]
leadership.columns = [x.replace('.', '_') for x in leadership.columns]
leadership.head(3).T

,0,1,2
congress,113,114,115
type,Assistant Democratic Leader,Assistant Majority Leader,Majority Whip
bioguideid,C001056,C001056,C001056
current,NaN,NaN,NaN

## os_legislators

In [11]:
os_legislators.columns = [x.lower() for x in os_legislators.columns]
os_legislators.columns = [x.replace('.', '_') for x in os_legislators.columns]
os_legislators = os_legislators.drop_duplicates()
os_legislators.head(3).T

,0,1,2
cid,N00050780,N00035774,N00026050
firstl,Mary Peltola,Dan Sullivan,Lisa Murkowski
lastnam,Peltola,Sullivan,Murkowski
party,D,R,R
offic,AK01,AKS1,AKS2
gend,F,M,F
first_elected,2022,2014,2002
xit_cod,0,0,0
commen,NaN,NaN,NaN
phon,NaN,202-224-3004,202-224-6665
fax,NaN,NaN,202-224-5301
w,NaN,https://www.sullivan.senate.gov,https://www.murkowski.senate.gov
webform,NaN,https://www.sullivan.senate.gov/contact/email,https://www.murkowski.senate.gov/public/index....
congress_offic,NaN,702 Hart Senate Office Building,522 Hart Senate Office Building
oguide_id,NaN,S001198,M001153
votesmart_id,NaN,NaN,15841.0
feccandid,NaN,S4AK00214,S4AK00099
witter_id,NaN,SenDanSullivan,LisaMurkowski
youtube_url,NaN,NaN,https://youtube.com/senatormurkowski
facebook_id,NaN,SenDanSullivan,SenLisaMurkowski
hd,NaN,1964-11-13,1957-05-22

In [12]:
newbio = ['B001311','B001313','B001314','B001315','C001125',
          'C001126','C001127','C001129','E000071','F000475','G000061',
          'G000551','G000595','H001093','L000595','L000597','M000687',
          'M001210','M001217','M001227','R000579','R000618',
          'S001218','T000165','T000488','P000619']
legs = ['Dan Bishop','Shontel Brown','Aaron Bean','Nikki Budzinski',
        'Troy Carter','Mike Carey','Sheila Cherfilus-McCormick',
        'Mike Collins','Jake Ellzey','Brad Finstad','Mike Garcia',
        'Raul M Grijalva','Bob Good','Erin Houchin','Julia Letlow',
        'Laurel Lee','Kweisi Mfume','Greg Murphy','Jared Moskowitz',
        'Jennifer McClellan','Pat Ryan','Pete Ricketts','Melanie Stansbury',
        'Tom Tiffany','Shri Thanedar','Mary Peltola']
def replacebio(b,n):
    os_legislators.loc[os_legislators['firstl']==n, 'oguide_id'] = b
for b, n in zip(newbio, legs):
    replacebio(b,n)

In [13]:
os_legislators = os_legislators[['cid', 'party', 'oguide_id']]
os_legislators = os_legislators.rename({'oguide_id': 'bioguideid'},
                                      axis=1)
os_legislators

           cid party bioguideid
0    N00050780     D    P000619
1    N00035774     R    S001198
2    N00026050     R    M001153
3    N00044245     R    C001054
4    N00041295     R    M001212
..         ...   ...        ...
532  N00032838     D    M001183
533  N00009771     R    C001047
534  N00049197     R    H001096
535  N00006236     R    B001261
536  N00029788     R    L000571

[536 rows x 3 columns]

In [14]:
members = pd.merge(congress_members, os_legislators,
                   on = 'bioguideid',
                  how = 'outer',
                  validate = 'one_to_one',
                  indicator = 'matched')

In [15]:
members['matched'].value_counts()

matched
both          530
left_only       7
right_only      6
Name: count, dtype: int64

In [16]:
members.query("matched=='left_only'")

,bioguideid,birthyear,currentmember,directordername,firstname,honorificname,invertedordername,lastname,officialwebsiteurl,state,...,depiction_imageurl,sponsoredlegislation_count,sponsoredlegislation_url,middlename,suffixname,nickname,district,cid,party,matched
120,N000147,1937.0,True,Eleanor Holmes Norton,ELEANOR,NaN,"Norton, Eleanor Holmes",NORTON,https://norton.house.gov/,District of Columbia,...,https://www.congress.gov/img/member/116_dg_dc_...,975.0,https://api.congress.gov/v3/member/N000147/spo...,HOLMES,NaN,NaN,NaN,NaN,NaN,left_only
133,S001177,1955.0,True,Gregorio Kilili Camacho Sablan,Gregorio,NaN,"Sablan, Gregorio Kilili Camacho",Sablan,https://sablan.house.gov/,Northern Mariana Islands,...,https://www.congress.gov/img/member/s001177_20...,149.0,https://api.congress.gov/v3/member/S001177/spo...,Kilili Camacho,NaN,NaN,NaN,NaN,NaN,left_only
248,P000610,1966.0,True,Stacey E. Plaskett,Stacey,Ms.,"Plaskett, Stacey E.",Plaskett,https://plaskett.house.gov/,Virgin Islands,...,https://www.congress.gov/img/member/116_dg_vi_...,112.0,https://api.congress.gov/v3/member/P000610/spo...,E.,NaN,NaN,NaN,NaN,NaN,left_only
252,R000600,1947.0,True,Aumua Amata Coleman Radewagen,Aumua Amata,Mrs.,"Radewagen, Aumua Amata Coleman",Radewagen,https://radewagen.house.gov/,American Samoa,...,https://www.congress.gov/img/member/r000600_20...,35.0,https://api.congress.gov/v3/member/R000600/spo...,Coleman,NaN,NaN,NaN,NaN,NaN,left_only
293,G000582,1976.0,True,Jenniffer González-Colón,Jenniffer,Miss,"González-Colón, Jenniffer",Gonzalez-Colon,https://gonzalez-colon.house.gov,Puerto Rico,...,https://www.congress.gov/img/member/g000582_20...,161.0,https://api.congress.gov/v3/member/G000582/spo...,NaN,NaN,NaN,NaN,NaN,NaN,left_only
478,M001219,1962.0,True,James C. Moylan,James,NaN,"Moylan, James C.",Moylan,https://moylan.house.gov,Guam,...,https://www.congress.gov/img/member/m001219_20...,12.0,https://api.congress.gov/v3/member/M001219/spo...,C.,NaN,NaN,NaN,NaN,NaN,left_only
536,B001320,1979.0,True,Laphonza R. Butler,Laphonza,Ms.,"Butler, Laphonza R.",Butler,https://www.butler.senate.gov/,California,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [17]:
members.query("matched=='right_only'")

,bioguideid,birthyear,currentmember,directordername,firstname,honorificname,invertedordername,lastname,officialwebsiteurl,state,...,depiction_imageurl,sponsoredlegislation_count,sponsoredlegislation_url,middlename,suffixname,nickname,district,cid,party,matched
537,G000551,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N00025284,D,right_only
538,F000062,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N00007364,D,right_only
539,C001129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N00035370,R,right_only
540,S001197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N00035544,R,right_only
541,C001084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N00032019,D,right_only
542,S001192,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N00033932,R,right_only

In [18]:
members = pd.merge(congress_members, os_legislators,
                  on = 'bioguideid',
                  how = 'inner')

In [19]:
members

,bioguideid,birthyear,currentmember,directordername,firstname,honorificname,invertedordername,lastname,officialwebsiteurl,state,...,depiction_attribution,depiction_imageurl,sponsoredlegislation_count,sponsoredlegislation_url,middlename,suffixname,nickname,district,cid,party
0,B000944,1952,True,Sherrod Brown,Sherrod,Mr.,"Brown, Sherrod",Brown,https://www.brown.senate.gov/,Ohio,...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/b000944_20...,1389.0,https://api.congress.gov/v3/member/B000944/spo...,NaN,NaN,NaN,NaN,N00003535,D
1,C000127,1958,True,Maria Cantwell,Maria,Ms.,"Cantwell, Maria",Cantwell,https://www.cantwell.senate.gov,Washington,...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/c000127_20...,882.0,https://api.congress.gov/v3/member/C000127/spo...,NaN,NaN,NaN,NaN,N00007836,D
2,C000141,1943,True,Benjamin L. Cardin,Ben,Mr.,"Cardin, Benjamin L.",Cardin,https://www.cardin.senate.gov/,Maryland,...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/c000141_20...,1265.0,https://api.congress.gov/v3/member/C000141/spo...,NaN,NaN,NaN,NaN,N00001955,D
3,C000174,1947,True,Thomas R. Carper,Thomas,Mr.,"Carper, Thomas R.",Carper,https://www.carper.senate.gov,Delaware,...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/c000174_20...,769.0,https://api.congress.gov/v3/member/C000174/spo...,R.,NaN,NaN,NaN,N00012508,D
4,C001070,1960,True,Robert P. Casey Jr.,Bob,Mr.,"Casey, Robert P., Jr.",Casey,https://www.casey.senate.gov/,Pennsylvania,...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/c001070_20...,1180.0,https://api.congress.gov/v3/member/C001070/spo...,NaN,JR.,NaN,NaN,N00027503,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,G000600,1988,True,Marie Gluesenkamp Perez,Marie,NaN,"Perez, Marie Gluesenkamp",Perez,https://gluesenkampperez.house.gov,Washington,...,Image courtesy of the Member,https://www.congress.gov/img/member/g000600_20...,13.0,https://api.congress.gov/v3/member/G000600/spo...,Gluesenkamp,NaN,NaN,3.0,N00050490,D
526,V000135,1969,True,Derrick Van Orden,Derrick,Mr.,"Van Orden, Derrick",Van Orden,https://vanorden.house.gov,Wisconsin,...,Image courtesy of the Member,https://www.congress.gov/img/member/v000135_20...,14.0,https://api.congress.gov/v3/member/V000135/spo...,NaN,NaN,NaN,3.0,N00046843,R
527,H001096,1962,True,Harriet M. Hageman,Harriet,NaN,"Hageman, Harriet M.",Hageman,https://hageman.house.gov,Wyoming,...,Image courtesy of the Member,https://www.congress.gov/img/member/h001096_20...,28.0,https://api.congress.gov/v3/member/H001096/spo...,M.,NaN,NaN,NaN,N00049197,R
528,R000618,1964,True,Pete Ricketts,Pete,Mr.,"Ricketts, Pete",Ricketts,https://www.ricketts.senate.gov,Nebraska,...,Official U.S. Senate Photo,https://www.congress.gov/img/member/r000618_20...,17.0,https://api.congress.gov/v3/member/R000618/spo...,NaN,NaN,NaN,NaN,N00027695,R
529,M001227,1972,True,Jennifer L. McClellan,Jennifer,NaN,"McClellan, Jennifer L.",McClellan,https://mcclellan.house.gov/,Virginia,...,Image courtesy of the Member,https://www.congress.gov/img/member/m001227_20...,5.0,https://api.congress.gov/v3/member/M001227/spo...,L.,NaN,NaN,4.0,N00051961,D

In [20]:
ideology = pd.read_csv('Data/ideology.csv')
ideology = ideology.rename({'bioguide_id':'bioguideid'}, axis=1)

In [21]:
members = pd.merge(members, ideology,
         on = 'bioguideid',
         how = 'inner')

## Voting similarity

In [22]:
votesim = pd.read_csv('Data/votingaffinity.csv')
votesim

        icpsr  member_compare  affinity_score
0       14226           14435        0.305147
1       14226           14858        0.375000
2       14226           14871        0.352941
3       14226           14921        0.772059
4       14226           15015        0.356618
...       ...             ...             ...
204133  91980           31101        0.202532
204134  91980           31102        0.830018
204135  91980           31103        0.169982
204136  91980           39301        0.198915
204137  91980           39307        0.202532

[204138 rows x 3 columns]

## os_contributions

In [23]:
os_contributions.columns = [x.lower() for x in os_contributions.columns]
os_contributions.columns = [x.replace('.', '_') for x in os_contributions.columns]
os_contributions = os_contributions.rename({'otal': 'total',
                                           'org_nam': 'org_name'}, axis=1)
os_contributions.head(30)

                                 org_name  total    pac   ndiv        cid
0                         State of Alaska  19541      0  19541  N00050780
1                 Sonosky, Chambers et al  16050      0  16050  N00050780
2               General Communication Inc  15150   2500  12650  N00050780
3                              Google Inc  14164      0  14164  N00050780
4          University of Alaska/Anchorage  13938      0  13938  N00050780
5                              Swing Left  13400      0  13400  N00050780
6                               Apple Inc  10783      0  10783  N00050780
7   Service Employees International Union  10010   5000   5010  N00050780
8                 National Education Assn  10000  10000      0  N00050780
9                           Sealaska Corp   9950      0   9950  N00050780
10                      Rpm International  66950  10000  56950  N00035774
11                          Goldman Sachs  59500   4000  55500  N00035774
12              Calfee, Halter & Griswold  45300      0  45300  N00035774
13    National Republican Senatorial Cmte  44600  44600      0  N00035774
14                       Trident Seafoods  43550   5600  37950  N00035774
15                     Elliott Management  39100      0  39100  N00035774
16                        General Atomics  37550  12500  25050  N00035774
17                         ConocoPhillips  37425  10000  27425  N00035774
18                       Blackstone Group  36100      0  36100  N00035774
19                             Lynden Inc  30700      0  30700  N00035774
20                         ConocoPhillips  60050  10000  50050  N00026050
21    American Israel Public Affairs Cmte  59500  10000  49500  N00026050
22                       Trident Seafoods  55300   5800  49500  N00026050
23    National Republican Senatorial Cmte  51200  51200      0  N00026050
24                               KKR & Co  48405      0  48405  N00026050
25                         NextEra Energy  36450  10000  26450  N00026050
26              General Communication Inc  34900  10000  24900  N00026050
27                            Exelon Corp  34300  11500  22800  N00026050
28                                 NorPAC  31250      0  31250  N00026050
29                          Capital Group  30700      0  30700  N00026050

## committees

In [24]:
committees.columns = [x.lower() for x in committees.columns]
committees.columns = [x.replace('.', '_') for x in committees.columns]
committees = committees.drop(['subcommittees'], axis=1)

In [25]:
committees['systemcode'] = [x[:-2].upper() for x in committees['systemcode']]

In [26]:
committees

,chamber,committeetypecode,name,systemcode,url,parent_name,parent_systemcode,parent_url
0,House,Other,Bicentenary Committee,HCZA,https://api.congress.gov/v3/committee/house/hc...,NaN,NaN,NaN
1,House,Standing,Energy (Ad Hoc) Committee,HHAH,https://api.congress.gov/v3/committee/house/hh...,NaN,NaN,NaN
2,House,Select,U.S. Role in Iranian Arms Committee,HLBZ,https://api.congress.gov/v3/committee/house/hl...,NaN,NaN,NaN
3,House,Select,"Children, Youth, and Families (Select) Committee",HLCF,https://api.congress.gov/v3/committee/house/hl...,NaN,NaN,NaN
4,House,Select,Select Committee on the Climate Crisis,HLCN,https://api.congress.gov/v3/committee/house/hl...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
709,Senate,Standing,"Competitiveness, Capital Formation and Economi...",SSSB,https://api.congress.gov/v3/committee/senate/s...,Small Business and Entrepreneurship Committee,sssb00,https://api.congress.gov/v3/committee/senate/s...
710,Senate,Standing,Advocacy and The Future of Small Business Subc...,SSSB,https://api.congress.gov/v3/committee/senate/s...,Small Business and Entrepreneurship Committee,sssb00,https://api.congress.gov/v3/committee/senate/s...
711,Senate,Standing,Small Business: Family Farm Subcommittee,SSSB,https://api.congress.gov/v3/committee/senate/s...,Small Business and Entrepreneurship Committee,sssb00,https://api.congress.gov/v3/committee/senate/s...
712,Senate,Standing,Entrepreneurship and Special Problems Facing S...,SSSB,https://api.congress.gov/v3/committee/senate/s...,Small Business and Entrepreneurship Committee,sssb00,https://api.congress.gov/v3/committee/senate/s...
713,Senate,Standing,Veterans' Affairs Committee,SSVA,https://api.congress.gov/v3/committee/senate/s...,NaN,NaN,NaN

## committee_members

In [27]:
committee_members.columns = [x.lower() for x in committee_members.columns]
committee_members.columns = [x.replace('.', '_') for x in committee_members.columns]
committee_members.head(30)

   committee_code  rank           title bioguide
0            HSII   1.0           Chair  W000821
1            HSII   1.0  Ranking Member  G000551
2            HSII   2.0             NaN  L000564
3            HSII   2.0             NaN  N000179
4            HSII   3.0             NaN  W000804
5            HSII   3.0             NaN  S001177
6            HSII   4.0             NaN  M001177
7            HSII   4.0             NaN  H001068
8            HSII   5.0             NaN  G000565
9            HSII   5.0             NaN  G000574
10           HSII   6.0             NaN  G000577
11           HSII   6.0             NaN  N000191
12           HSII   7.0             NaN  R000600
13           HSII   7.0             NaN  L000593
14           HSII   8.0             NaN  L000578
15           HSII   8.0             NaN  P000618
16           HSII   9.0             NaN  W000806
17           HSII   9.0             NaN  L000273
18           HSII  10.0             NaN  G000582
19           HSII  10.0             NaN  S001218
20           HSII  11.0             NaN  F000469
21           HSII  11.0             NaN  P000619
22           HSII  12.0             NaN  S001212
23           HSII  12.0             NaN  O000172
24           HSII  13.0             NaN  C001114
25           HSII  13.0             NaN  M001225
26           HSII  14.0             NaN  T000165
27           HSII  14.0             NaN  H001094
28           HSII  15.0             NaN  C001054
29           HSII  15.0             NaN  K000400

## Create the database

In [28]:
dbserver = psycopg2.connect(
    host = 'postgres',
    user = 'postgres',
    password = POSTGRES_PASSWORD,
    port = 5432
)
dbserver.autocommit = True

In [29]:
cursor = dbserver.cursor()

In [30]:
try:
    cursor.execute('CREATE DATABASE congress')
except:
    cursor.execute('DROP DATABASE congress')
    cursor.execute('CREATE DATABASE congress')

In [31]:
engine = create_engine('postgresql+psycopg2://{user}:{password}@{host}:{port}/{db}'.format(
    user = 'postgres',
    password = POSTGRES_PASSWORD,
    host = 'postgres',
    port = 5432,
    db = 'congress'
))

We need to upload

* members
* bills
* committees
* committee members
* terms
* leadership
* contributions

In [32]:
print(members.shape[0])
members.to_sql('members', con=engine, index=False, chunksize=1000, if_exists = 'replace')

530

530

In [33]:
print(bills.shape[0])
bills.to_sql('bills', con=engine, index=False, chunksize=1000, if_exists = 'replace')

38325

38325

In [34]:
print(committees.shape[0])
committees.to_sql('committees', con=engine, index=False, chunksize=1000, if_exists = 'replace')

714

714

In [35]:
print(committee_members.shape[0])
committee_members.to_sql('committee_members', con=engine, index=False, chunksize=1000, if_exists = 'replace')

3866

3866

In [36]:
print(terms.shape[0])
terms.to_sql('terms', con=engine, index=False, chunksize=1000, if_exists = 'replace')

278

278

In [37]:
print(leadership.shape[0])
leadership.to_sql('leadership', con=engine, index=False, chunksize=1000, if_exists = 'replace')

79

79

In [38]:
print(os_contributions.shape[0])
os_contributions.to_sql('contributions', con=engine, index=False, chunksize=1000, if_exists = 'replace')

1990

1990

In [39]:
print(votesim.shape[0])
votesim.to_sql('votesim', con=engine, index=False, chunksize=1000, if_exists = 'replace')

204138

204138

In [41]:
votesim

        icpsr  member_compare  affinity_score
0       14226           14435        0.305147
1       14226           14858        0.375000
2       14226           14871        0.352941
3       14226           14921        0.772059
4       14226           15015        0.356618
...       ...             ...             ...
204133  91980           31101        0.202532
204134  91980           31102        0.830018
204135  91980           31103        0.169982
204136  91980           39301        0.198915
204137  91980           39307        0.202532

[204138 rows x 3 columns]